server:
  port: 9001
  servlet:
    context-path: /api/medications

spring:
  application:
      name: medication-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8080/eureka/
    instance:
      hostname: localhost
      prefer-ip-address: true