#server:
#  port: 9001
#  servlet:
#    context-path: /api/medications
#
#spring:
#  application:
#      name: medication-service
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#
#eureka:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka/
#    instance:
#      hostname: localhost
#      prefer-ip-address: true


spring:
  application:
    name: medication-service
  config:
    import: "optional:configserver:http://localhost:8088"